// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnoxslgdobkfvgdckvyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNub3hzbGdkb2JrZnZnZGNrdnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTk4NzYsImV4cCI6MjA2MDUzNTg3Nn0.zqQ2ncuBAbxnuaX0ESMuWBhwz7LgX5bxI8jJgw0Qsbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);